<a href="https://colab.research.google.com/github/mailnami-coder/python-basics/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How do we write matrics? list of list inside tuple

In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrix addition and substraction

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Addition:\n",A+B)
print("Substrction:\n",A-B)

Addition:
 [[ 6  8]
 [10 12]]
Substrction:
 [[-4 -4]
 [-4 -4]]


Singular matrix - A square matrix is a singular matrix if the determinant of the matrix is zero

Inverse of a matrix - Mathematically, a square matrix A of size n * n is invertible if there exists another matrix B of the same size such that
A*B=B*A=I
The matrix B is known as the inverse of A and is denoted as A⁻¹

Determinant of a mtrix - History. Historically, determinants were used long before matrices: A determinant was originally defined as a property of a system of linear equations. The determinant "determines" whether the system has a unique solution (which occurs precisely if the determinant is non-zero).

In [ ]:
import numpy as np
A=np.array([[3,4],[5,6]])
det=np.linalg.det(A)
print("determinant:\n",det)
inv_mat=np.linalg.inv(A)
print("Inverse:\n",inv_mat)

determinant:
 -1.9999999999999971
Inverse:
 [[-3.   2. ]
 [ 2.5 -1.5]]
